### ISSUE TITLE
1.0 .bwextension not "seen" by Bitwig 2.5b7

### ISSUE THREAD

**Issue by yokaiichi** [dgmulf/Twister4Bitwig#1]
The MFT template loads just fine from the MidiFighter Utility, but putting the corresponding *.bwextension in the Extensions folder for Bitwig has no effect. Bitwig does not "see" it and does not load it. Nothing appears in Settings > Controllers, and there is no successful load message during Bitwig startup. This is on a Windows 10 system with Bitwig 2.5b7.

**Comment by dgmulf** [comment]
The old extension spelled the hardware vendor "DjTechTools" all in one word, but I have stylized it as "DJ TechTools", so it will create a new category in your list of controller extensions. Is this what you're looking for?

**Comment by yokaiichi** [comment]
Ah, I see now. Thank you. For some reason, the old controller extension by Pawnbroker would automatically load itself into Settings > Controllers, but yours requires the user to manually do Settings > Add > DJ TechTools > MidiFighter Twister...
